# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126
os_type: centos

tasks:
- install:
    flavor: notcmalloc
- ceph:
- openssl_keys:

overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw enable static website: True
      client.0:
        rgw lc debug interval: 10
      client.1:
        rgw enable apis: s3website
