tasks:
- dnsmasq:
    client.0:
      s3.: client.0
      s3-website.: client.1
- rgw:
    client.0:
      port: 80
      dns-name: s3.
      valgrind: [--tool=memcheck]
    client.1:
      port: 80
      dns-s3website-name: s3-website.
      valgrind: [--tool=memcheck]
- s3tests:
    client.0:
      force-branch: ceph-master
      rgw_server: client.0
      rgw_website_server: client.1
