
overrides:
  ceph:
    conf:
      global:
        ms type: simple
    log-whitelist:
      - client session with non-allowable root

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_sessionmap
