meta:
- desc: |
   install ceph/luminous latest
tasks:
- install:
    branch: luminous
- print: "**** done installing luminous"
- ceph:
    log-whitelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
- exec:
    osd.0:
      - ceph osd require-osd-release luminous
      - ceph osd set-require-min-compat-client luminous
- print: "**** done ceph"
